[Mentoring-T-119] 코틀린 로또 게임 리뷰 부탁드립니다. - 김희준
BI-kotlin-in-action-2ND/Heejune-Lotto pull request #1
Opened 2024-02-05 02:23 UTC by Heejun-0219

안녕하세요,

현재 자동 로또 번호 생성, 수동 번호 입력, 당첨 번호 확인 등의 핵심 기능을 구현하였으며, 프로그램의 기본 흐름은 완성되었습니다.

#### 주요 고민사항:
1. **도메인 객체의 적절한 사용**: 도메인 모델(`LottoTicket`, `WinningLotto` 등)이 객체지향 원칙에 맞게 잘 구현되었는지, 객체 간의 관계와 책임이 적절한지 리뷰 부탁드립니다.
2. **패키지 구조**: 현재 패키지가 기능별로 적절히 나누어져 있는지, 개선할 점이 있는지 조언해 주시면 감사하겠습니다.
3. **전략 패턴 적용**: 자동과 수동 로또 번호 생성 로직에 전략 패턴을 적용하고 싶었으나, 설계 초기 단계에서 고려하지 못했습니다. 이에 대한 적용 방법이나 설계 개선 방향에 대한 조언을 구합니다.
4. **`LottoGame` 객체의 싱글톤 관리**: `AppConfig`를 통해 `LottoGame` 인스턴스를 애플리케이션 전반에서 싱글톤처럼 관리하고자 했으나, 구현에 어려움을 겪었습니다. 이 부분에 대한 구현 조언 또는 대안적인 관리 방법이 있다면 알려주시기 바랍니다.

#### 추가적인 피드백 요청:
- 코드의 가독성 및 유지보수성에 대한 일반적인 조언
- 객체지향 설계 원칙 및 패턴 적용에 있어서의 개선점

감사합니다.

2024-02-05 12:23 UTC, konempty requested changes
크 역시 한번 해보셔서 그런지 빠르게 올려주셨네요 ㅋㅋㅋ 👍 👍 
리뷰 조금 드렸는데 확인해보시고 반영 부탁드립니다~!

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/controller/GameController.kt
> +    fun start(remainMoney: Int = 0): Int {
오호 여기에서 디폴트 매개변수를 사용하신 이유가 있을까요??

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/domain/LottoGame.kt
> +                else -> PrizeCategory.NONE
오 ㅋㅋㅋㅋ 요런 코드는 처음 보는데 정말 마음에 드는 코드네요
다음엔 저도 요런식으로 해봐야겠어요!

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/domain/LottoTicket.kt
> +        require(numbers.all { it in 1..45 }) { "로또 번호는 1부터 45 사이여야 합니다" }
1...45도 로또 숫자라는 도메인을 나타내는 정보일것 같아요!
따라서 LottoTicket이 가지기에는 좀 역할에 안맞는 느낌이라 로또 숫자를 별도의 도메인으로 빼면 좋을것 같고
요럴때 좋은게 코틀린의 value class 인데 그걸 활용해보시면 좋을것 같습니다~!

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/domain/LottoTicket.kt
> +        return numbers.count { it in winningNumbers }
요거 O(n^2) 비교네요
O(N log N)으로 줄여볼순 없을까요??

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/domain/LottoTicket.kt
> +        return numbers.contains(target)
제 피드백을 이해한다면 요것도 O(N)로직에서 O(log N)으로 줄여볼수 있을것 같습니다~!

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/domain/generator/AutoLottoGenerator.kt
> +    private val numberCount: Int = 6,
numberRange와 numberCount가 프로그램이 진행되면서 변경될 일이 있을까요??
상수같은걸로 처리하면 좋을것 같아요!

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/domain/generator/AutoLottoGenerator.kt
> +        val numbers = numberRange.shuffled().take(numberCount).sorted()
크 제가 바라던 코드입니다
역시 이전에 해보셔서 그런지 바로 요렇게 랜덤 추출하시는군요 👍 👍

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        return (1..purchaseMoney).map { autoLottoGenerator.generate() }
오호 코드의 의도는 이해가 가는데 개인적으로는 뭔가 가독성이 떨어져 보이네요 ㅋㅋㅋ..
그래도 요 대로 두셔도 좋을것 같습니다~!

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/view/InputView.kt
> +import java.util.*
오노 ㅠㅠㅠ
와일드 카드 임포트는 지양해야합니다 ㅠㅠㅠ
IDE 설정에서 와일드 임포트가 되지 않도록 설정 부탁드립니다

https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij

2024-02-05 12:23 UTC, konempty commented on src/test/kotlin/domain/WinningLottoTest.kt
> +    fun `로또 번호 실패 테스트`() {
요건 갠취인데 한개의 테스트는 한개의 케이스만 확인해야한다고 생각을 해서
저는 요렇게 한개의 테스트가 여러개의 Assert문을 가지는걸 별로 선호하지 않습니다..!

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/config/AppConfig.kt
> +    val userInputController = UserInputController(this)
요게 꽤 위험한 코드인데
AppConfig를 만드려면 userInputController가 필요하고 
UserInputController를 만드려면 다시 AppConfig가 필요한
요 관계를 순환참조관계? 라고 부르면서 안티패턴으로 자주 나와요

이런 관계가 잘못하면 프로그램 터트리기 딱좋거든요 ㅋㅋㅋㅋ

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/controller/GameController.kt
> +        autoLottoTickets: List<LottoTicket>,
약간 첨언이긴 한데 프로그램 전역적으로 List<LottoTicket>으로 돌아다니는게 예쁘지는 않네요 ㅋㅋㅋ..
일급 컬렉션을 써보시면 좋을것 같습니다~!

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/domain/LottoGame.kt
> +    fun calculateResults(): Map<PrizeCategory, Int> {
요기 Map도 결과를 관리하기위한 일급객체를 사용하면 좋을것 같구요

LottoService의 calculateTotalEarningPercentage메소드를 해당 객체가 수행할수 있으면 역할이 분리되는것 같아서
좋을것 같아요!

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        return manualLottoGenerator.generate(manualNumbers)
요건 코드의 느낌이 좀 어색한데
manualLottoGenerator가 로또를 생성해내는 느낌이 아니라
외부에서 다 알려주고 manualLottoGenerator가 그에 맞춰 따라가는 느낌이네요
manualNumbers를 manualLottoGenerator가 내부적으로 생성하는 느낌이 들도록 할수 없을까요??

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        }.sum()
으흠 요건 TMI같아서 리뷰 드리는게 맞나 싶긴한데
요 코드드는 totalResult -> List<Int> -> Int 요렇게 2단계를 거쳐서 계산이 되구요
아주 조금더 효율적인 코드는
```kotlin
totalResult.entries.sumOf{ category.prize * count }
```
요거예요
Map의 entries는 미리 계산된 값이라 반복문을 돌지 않고 추가적인 메모리를 잡아먹지 않거든요 ㅋㅋㅋ
요게 맵이 작으면 상관 없는데
맵이 엄청 거대하다면 성능 차이가 아주 조금 있을수도 있습니다 ㅋㅋㅋ

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/view/InputView.kt
> +            ?.map { it.trim().toIntOrNull() ?: throw IllegalArgumentException(INVALID_INPUT_MESSAGE) }
요코드를 줄이면
?.map { requireNotNull(it.trim().toIntOrNull()) {INVALID_INPUT_MESSAGE} }
가 되겠네요!

2024-02-05 12:23 UTC, konempty commented on src/test/kotlin/domain/generator/ManualLottoGeneratorTest.kt
> +        }
크 테스트도 짜시다니 너무 좋습니다 👍 👍 
정석적인 테스트라 마음에 드는데
한가지만 더 첨언해드리면 너무 자바스러운 테스트라서
kotest를 사용해보신다면 좀더 코틀린스럽지 않을까 싶습니다 ㅎㅎ

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/domain/LottoGame.kt
> +        userLottoTickets.forEach { lottoTicket ->
forEach보다 map{}을 썼다면 좀더 예뻤을것 같아요! ㅋㅋㅋ
result라는 추가 변수도 불필요해질것 같구요

2024-02-05 12:23 UTC, konempty commented on src/main/kotlin/domain/LottoGame.kt
> +                else -> PrizeCategory.NONE
요 역할은 PrizeCategory가 하면 좋을것 같은데 어떻게 생각하시나요??
PrizeCategory.getPrize(matchCount, hasBonus)
요런 느낌으로요!

2024-02-06 00:08 UTC, Heejun-0219 commented on src/main/kotlin/controller/GameController.kt
> +    fun start(remainMoney: Int = 0): Int {
처음 로또를 실행할 때도 0이 인자로 들어오긴 하지만, 저렇게 놔두는 게 다른 사람이 코드를 읽을 때 이해하기 쉬울 거 같아서 고치지 않고 놔뒀습니다!

2024-02-06 00:09 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoGame.kt
> +                else -> PrizeCategory.NONE
오 감사합니다

저도 enum에서 뭔가 더 해주면 좋겠다 싶었는데 한번 바꿔보겠습니다

2024-02-06 04:35 UTC, Heejun-0219 commented on src/main/kotlin/view/InputView.kt
> +import java.util.*
헉 확인했습니다

2024-02-06 04:40 UTC, Heejun-0219 commented on src/test/kotlin/domain/WinningLottoTest.kt
> +    fun `로또 번호 실패 테스트`() {
테스트 내에서 어떤 assert문이 실패하던 똑같은 테스트명이 출력되어 판단하기 어렵기 때문일까요??

2024-02-06 04:47 UTC, Heejun-0219 commented on src/main/kotlin/config/AppConfig.kt
> +    val userInputController = UserInputController(this)
```kotlin
class AppConfig {
    val inputView = InputView
    val outputView = OutputView
    val autoLottoGenerator = AutoLottoGenerator()
    val manualLottoGenerator = ManualLottoGenerator()
    val lottoService = LottoService(autoLottoGenerator, manualLottoGenerator)
    val userInputController = UserInputController(inputView, outputView, lottoService)
}
```

다음과 같이 고쳐봤습니다! 이렇게 고치는게 맞는지는 모르겠지만, 그래도 안티패턴 하나 더 알아갑니다,, 감사합니다

2024-02-06 04:53 UTC, Heejun-0219 commented on src/main/kotlin/service/LottoService.kt
> +        }.sum()
`return totalResult.entries.sumOf { it.key.prize * it.value }`

오 그래서 IDE가 value() 대신 enrties를 추천하는 걸까요?

2024-02-06 04:57 UTC, Heejun-0219 commented on src/main/kotlin/view/InputView.kt
> +            ?.map { it.trim().toIntOrNull() ?: throw IllegalArgumentException(INVALID_INPUT_MESSAGE) }
와 코드를 줄이면서 가독성 높이는 게 쉽지 어렵네요

2024-02-06 05:20 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoGame.kt
> +        userLottoTickets.forEach { lottoTicket ->
result를 써야 하나 고민하긴 했는데 그냥 간단하게 map을 쓰면 해결되는군요

2024-02-06 05:21 UTC, Heejun-0219 commented on src/main/kotlin/domain/generator/AutoLottoGenerator.kt
> +        val numbers = numberRange.shuffled().take(numberCount).sorted()
오옷 감사합니다!

2024-02-06 05:22 UTC, Heejun-0219 commented on src/main/kotlin/service/LottoService.kt
> +        return (1..purchaseMoney).map { autoLottoGenerator.generate() }
이렇게도 될까 하고 써보긴 했는데,, 역시 가독성이 떨어지는거 같네요

2024-02-06 05:39 UTC, Heejun-0219 commented on src/test/kotlin/domain/generator/ManualLottoGeneratorTest.kt
> +        }
오 제대로 사용한 건지는 모르겠지만, 가독성이 훨씬 좋은거 같다는 생각이 듭니다!

2024-02-06 05:44 UTC, Heejun-0219 commented on src/main/kotlin/service/LottoService.kt
> +        return manualLottoGenerator.generate(manualNumbers)
입력채로 리스트로 넘겨서 생성기 안에서 .map를 사용하도록 변경했습니다!

```kotlin
    fun generate(manualNumbers: List<List<Int>>): List<LottoTicket> {
        return manualNumbers.map { LottoTicket(it) }
    }
```

아직 일급 객체는 구현을 못해서 리스트로 뒀습니다.

2024-02-06 07:36 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoTicket.kt
> +        require(numbers.all { it in 1..45 }) { "로또 번호는 1부터 45 사이여야 합니다" }
value class를 활용하는 게 어려워서 일단 해보긴 했는데 이게 정말 맞나,,,, 잘 모르겠습니다.

```kotlin
open class LottoTicket(val numbers: List<Int>) {
    init {
        LottoNumbersCheck(numbers)
    }
```

```kotlin
@JvmInline
value class LottoNumbersCheck(private val numbers: List<Int>) {
    init {
        require(numbers.size == 6) { LottoConfig.ERROR_MESSAGE_LOTTO_SIZE }
        require(numbers.distinct().size == 6) { LottoConfig.ERROR_MESSAGE_DUPLICATE }
        require(numbers.all { it in (LottoConfig.START_NUMBER..LottoConfig.END_NUMBER) }) { LottoConfig.ERROR_MESSAGE_NUMBER_RANGE }
    }
}

```

2024-02-06 08:05 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoTicket.kt
> +        return numbers.count { it in winningNumbers }
```kotlin 
    fun match(winningNumbers: List<Int>): Int {
        return numbers.intersect(winningNumbers.toSet()).size
    }

    fun hasBonus(target: Int): Boolean {
        return target in numbers
    }
```

다음과 같이 고쳐보았습니다..

2024-02-06 08:08 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoTicket.kt
> +        return numbers.contains(target)
```kotlin
    fun hasBonus(target: Int): Boolean {
        return numbers.binarySearch(target) >= 0
    }
``` 

이렇게 하면 시간복잡도가 줄어들거 같습니다!

2024-02-06 08:12 UTC, Heejun-0219 commented on src/main/kotlin/domain/generator/AutoLottoGenerator.kt
> +    private val numberCount: Int = 6,
```kotlin
object LottoConfig {
    const val START_NUMBER = 1
    const val END_NUMBER = 45
    const val LOTTO_TICKET_SIZE = 6
    const val ERROR_MESSAGE_LOTTO_SIZE = "로또 번호는 6개여야 합니다."
    const val ERROR_MESSAGE_DUPLICATE = "로또 번호는 중복되지 않아야 합니다."
    const val ERROR_MESSAGE_NUMBER_RANGE = "로또 번호는 1부터 45 사이여야 합니다."
    const val MANUAL_GENERATOR_NOT_SUPPORTED = "수동 로또 생성기는 수동으로 번호를 입력해야 합니다"
    const val BLANK = ""
    const val AUTO_MODE = "A"
}
```

찾아보고 object로 만들었는데 정적 클래스..? 처럼 사용하는 게 맞을까요?

2024-02-06 13:56 UTC, konempty commented
아직.. 반영중이신거죠..?? ㅋㅋㅋㅋ
혹시 리뷰 재요청을 잊으셨을까봐 리마인드차 댓글 남깁니다~!

2024-02-06 14:10 UTC, Heejun-0219 commented on src/main/kotlin/controller/GameController.kt
> +        autoLottoTickets: List<LottoTicket>,
뭔가 마지막에 일급 컬렉션을 만드니까 앞에 피드백을 해결한 것들이 무마되는 느낌이네요,,, 
좀 슬프지만 다시 천천히 고쳐보겠습니다.

2024-02-07 00:16 UTC, Heejun-0219 commented
어제 하다가 잠들고 그래서 이제야 다 했습니다! 맘에 들지는 않지만,,, 그래도 피드백을 너무 늦게 받으면 안 되니,,, 부탁드리겠습니다

2024-02-07 15:26 UTC, konempty requested changes
고생이 많으시네요 ㅠㅠ 쪼금만더 수정 부탁드립니다

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/controller/GameController.kt
> +    fun start(remainMoney: Int = 0): Int {
오호 저는 오히려 디폴드 매개변수가 있어서 불편했는데
그렇다면 그대로 두셔도 좋습니다~!

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/config/LottoConfig.kt
> +    const val AUTO_MODE = "A"
각각의 상수를 사용하는곳에서 static 변수를 선언하는걸 기대하긴 했는데
요렇게 상수를 모아두는 클래스를 만들어 두는것도 갠취로 인정할만 할것 같네요 ㅋㅋㅋㅋ
다만 클래명을 조금더 직관적으로 상수들을 모아두는 클래스 라는걸 알수 있도록 지어두면 좋을것 같습니다~!

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/LottoGame.kt
> +    }
요 클래스의 역할은 등수를 계산하고 결과를 계산해내는데
클래스 명은 너무 추상적으로 잡혀있는것 같아요 ㅠㅠ
좀더 직관적인 이름으로 바꿔주세요

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/LottoResult.kt
> +    fun earningMoney(): Int = PrizeCategory.earningMoney(this)
PrizeCategory의 메소드에 this를 넘기는것 보다
차라리 요 LottoResult 클래스 내부에서 계산하는게 더 역할 분리가 잘된것 같고
LottoResult라는 도메인의 의도가 잘 살아날것 같아요..!
calculateTotalEarningPercentage도 비슷한 결이구요

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/check/LottoNumbersCheck.kt
> +    }
value class는 한개의 **값**을 관리, 검증, 계산하는 클래스인데
요 클래스의 의도는 numbers를 검증을 하는 용도로만 사용하고 있네요

제가 정답을 직접 알려드리는걸 싫어하지만 요건 설명을 하기가 너무 까다로워서 
사용방법을 보여드릴게요..!
<img width="577" alt="스크린샷 2024-02-07 오후 11 50 08" src="https://github.com/BI-kotlin-in-action-2ND/Heejune-Lotto/assets/44064530/32de3c6a-2165-4807-b474-7115e4a4b0aa">

요렇게 로또 번호 하나를 랩핑해서 하나의 **값**만을 가지는게 value class의 사용방법입니다~!
TMI이긴한데 value class의 동작과정이 바이트 코드로 바꿔보면 꽤 재미잇거든요 
시간 있으시면 찾아보시는걸 추천해드리고 그렇게 하면 \@JvmInline라는 독특한 어노테이션이 강제되는 이유도
자연스럽게 깨우치실수 있을거라 기대합니다 ㅎㅎㅎ

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/generator/ManualLottoGenerator.kt
> +    }
요건 제 의도와 다르네요 ㅠㅠ
제 의도는 
val lotto = ManualLottoGenerator. generate()
혹은 

val lotto = ManualLottoGenerator. generate(some_lambda)
요런 코드가 가능한걸 의도했어요 ㅠㅠ

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/generator/ManualLottoGenerator.kt
> +    }
오히려 파라메터가 없는 상속 받은 메소드가 사용 불가해지니까 이러면 상속받는 의미가 있나? 싶더라구요

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/view/InputView.kt
> +                ?: throw IllegalArgumentException(INVALID_INPUT_MESSAGE)
?: throw IllegalArgumentException(INVALID_INPUT_MESSAGE)
를 두번 연속으로 쓰신이유가 있을까요..?? ㅋㅋㅋ

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/view/InputView.kt
> +                ?: throw IllegalArgumentException(INVALID_INPUT_MESSAGE)
그리고 여기도 이전에 리뷰드린 requireNotNull를 활용할수 있을것 같아요~!

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/view/InputView.kt
> +        return readlnOrNull()?.toIntOrNull() ?: throw IllegalArgumentException(INVALID_INPUT_MESSAGE)
여기도 requireNotNull 가능해보이구요

2024-02-07 15:26 UTC, konempty commented on src/test/kotlin/domain/generator/AutoLottoGeneratorKotest.kt
> +    }
jUnit과 kotest 테스트가 혼재되어있는데 하나로 통일해주시면 좋을것 같아요~!

2024-02-07 15:26 UTC, konempty commented on src/test/kotlin/domain/generator/ManualLottoGeneratorTest.kt
> +    }
<img width="325" alt="스크린샷 2024-02-08 오전 12 06 03" src="https://github.com/BI-kotlin-in-action-2ND/Heejune-Lotto/assets/44064530/2a7f850e-73e7-4c36-a0c8-75424f6bbc6b">

테스트 커버리지가 생각보다 많이 낮네요 ㅠㅠ
클래스 커버리지는 50%이상 라인 커버리지는 40%까지 올려주세요

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/LottoTicket.kt
> +        return numbers.intersect(winningNumbers.toSet()).size
winningNumbers.toSet()의 복잡도는 O(N log N)입니다
또한 intersect의 복잡도도 O(N log N)입니다
따라서 전체 코드의 O(N log N)가 맞긴 하겠네요
단, 로또의 개수가 1억개라면 비교를 위해 winningNumbers.toSet()를 1억번 실행해야겠네요
winningNumbers가 Set<Int>형이라면 winningNumbers.toSet()를 여러번 할필요가 없지 않았을까요??

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/LottoTicket.kt
> +        return numbers.binarySearch(target) >= 0
이 코드엔 문제가 하나있네요
희준님은 요 코드를 개발한 담당자니까 numbers가 이미 정렬이 되어있다는걸 알수 있고 
binarySearch가 정상 작동할거라는 믿음을 가질수 있겠지만
요 코드를 보는 타인은 List<Int>형이니까 정렬이 되어있지 않을수도 있지 않을까 라는 의심에 빠질수도 있어요 ㅠㅠ
이 문제를 어떻게 해결할수 있을까요??

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/PrizeCategory.kt
> +            else -> NONE
각 enum들이 보너스 일치 여부까지 알고 있다면 좀더 효율적인 코드를 만들어 낼수 있을것 같아요!
```kotlin
enum class PrizeCategory(val prize: Int, val matchCount: Int, val hasBonus: Boolean) {
    FIRST(100_000, 6, false),
    SECOND(50_000, 5, true),
    THIRD(100, 5, false),
// 중략

        fun getRank(
            matchCount: Int,
            hasBonus: Boolean,
        ) = entries.find { it.hasBonus == hasBonus && it.matchCount == matchCount } ?: NONE
```

요렇게 말이죠!

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/check/BonusLottoNumbersCheck.kt
> +value class BonusLottoNumbersCheck(private val numbers: List<Int>) {
요 클래스도 value class에 부합하지 않는 사용처네요 ㅠㅠ

2024-02-07 15:26 UTC, konempty commented on src/main/kotlin/domain/generator/AutoLottoGenerator.kt
> +        val bonusNumber = (numberRange - numbers.toSet()).shuffled().first()
요 코드를 조금이나마 줄여보면
`        val bonusNumber = (numberRange - numbers.toSet()).random()`
요렇게 할수 있을것 같아요~!

2024-02-07 15:26 UTC, konempty commented on src/test/kotlin/domain/WinningLottoTest.kt
> +    fun `로또 번호 실패 테스트`() {
네넵 그 이유가 가장 큽니다 ㅋㅋㅋ

2024-02-07 15:26 UTC, konempty commented on src/test/kotlin/domain/generator/AutoLottoGeneratorKotest.kt
> +class AutoLottoGeneratorKotest : FunSpec({
요건 리뷰는 아니고 단순 코멘트 인데
FunSpec 말고도 kotest의 많은 테스트 스펙이 있는데 각각의 사용처와 사용 방법을
알아두시면 도움이 될것 같습니다~!
프레임 워크(스프링, 안드로이드 등)을 사용하다보면 FunSpec으로는 표현하기 어렵거나 
공통된 코드를 가지는 테스트가 많아지거든요

2024-02-07 15:26 UTC, konempty commented on src/test/kotlin/domain/generator/AutoLottoGeneratorTest.kt
> +        val generator = AutoLottoGenerator()
예측 불가능한 랜덤을 테스트 하는건 별로 좋지 않습니다 ㅠㅠ
실패해야하는 테스트가 운이 좋아 성공하는 케이스도 만들어 질수도 있고
랜덤은 개발자의 의도를 담기가 까다롭거든요 ㅠㅠ

2024-02-07 21:28 UTC, Heejun-0219 commented on src/test/kotlin/domain/WinningLottoTest.kt
> +    fun `로또 번호 실패 테스트`() {
역시 테스트도 올바르게 잘 써야,,,

2024-02-07 21:28 UTC, Heejun-0219 commented on src/main/kotlin/controller/GameController.kt
> +    fun start(remainMoney: Int = 0): Int {
오오 네넵!

2024-02-07 21:32 UTC, Heejun-0219 commented on src/main/kotlin/config/LottoConfig.kt
> +    const val AUTO_MODE = "A"
아,,,헉,,,
```kotlin 
class LottoConstant {
    companion object {
        val ERROR_MESSAGE_NUMBER_RANGE: String = "로또 번호는 1부터 45 사이여야 합니다."
    }
}
```
 요렇게 쓰는 게 원래 얘기한 신 걸까요...?

2024-02-07 21:38 UTC, Heejun-0219 commented on src/main/kotlin/config/LottoConfig.kt
> +    const val AUTO_MODE = "A"
저는 자바할 때, constant로 모아 놓은 걸 좋아했었어서 그래도 클래스명을 좀 더 신경 써야겠네요!

2024-02-07 21:52 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoGame.kt
> +    }
항상 이름 짓기가 문제도 어렵네요 ㅠ
좀 더 직관적으로 만들게 노력해 보겠습니다!

`LottoPrizeCalculator`

2024-02-07 22:01 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoResult.kt
> +    fun earningMoney(): Int = PrizeCategory.earningMoney(this)
음 그렇다면 enum 클래스는 계산하는 기능을 많이 사용하지 않는 게 일반적일까요?

2024-02-07 23:59 UTC, Heejun-0219 commented on src/main/kotlin/domain/generator/ManualLottoGenerator.kt
> +    }
```kotlin 
fun manualLottoGenerator(manualNumbers: List<List<Int>>): LottoTickets {
        val manualLottoTickets = manualNumbers.map { manualLottoGenerator.generate(it) }
        return LottoTickets(manualLottoTickets)
    }
```

ManualGenerator.generator에 람다를 인자로 넘겨주는 것보다 manualNumbers에 .map를 적용하는 게 나을 거 가아서 변경해 보았습니다

2024-02-08 00:11 UTC, Heejun-0219 commented on src/main/kotlin/domain/generator/ManualLottoGenerator.kt
> +    }
처음에 생각할 때는 인터페이스 하나로 수동 생성기와 자동 생성기를 나눠서 사용자의 선택에 따라 갈아 끼우는 방식을 생각했는데 생각을 잘못해서 아예 인터페이스가 쓸모 없어진 거 같아서 좀 슬퍼요,,

2024-02-08 00:15 UTC, Heejun-0219 commented on src/main/kotlin/view/InputView.kt
> +                ?: throw IllegalArgumentException(INVALID_INPUT_MESSAGE)
```kotlin
        return (1..count).map {
            readlnOrNull()?.split(',')
                .map { requireNotNull(it.trim().toIntOrNull()) { INVALID_INPUT_MESSAGE } }
        }
```
?.map를 사용하게 되면 List<List<Int>?> 타입이 되어서 TYPE mismatch 오류가 나오더라구요

그래서 ?.map -> .map으로 변경했는데 이는 안전성에 문제가 될까요..?

2024-02-08 00:16 UTC, Heejun-0219 commented on src/main/kotlin/view/InputView.kt
> +        return readlnOrNull()?.toIntOrNull() ?: throw IllegalArgumentException(INVALID_INPUT_MESSAGE)
애초에 다 확인했어야 하는데,,, 죄송합니다

2024-02-08 05:55 UTC, Heejun-0219 commented on src/test/kotlin/domain/generator/AutoLottoGeneratorKotest.kt
> +    }
코틀린스럽게 kotest로다가,,,, 통합해보곘습니다

2024-02-08 07:35 UTC, Heejun-0219 commented on src/main/kotlin/domain/PrizeCategory.kt
> +            else -> NONE
와,,,, 이 클래스만 바꾸면 되는 진짜 감탄,,,,하고 갑니다,,,

2024-02-24 09:14 UTC, Heejun-0219 commented on src/test/kotlin/domain/generator/ManualLottoGeneratorTest.kt
> +    }
최대한 올리긴 했는데 inputview와 outputview가 존재하는 controller는 어떻게 테스트해야 할지 고민입니다

2024-02-24 09:15 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoTicket.kt
> +        return numbers.intersect(winningNumbers.toSet()).size
로또 번호를 TreeSet으로 저장할까 고민하다가 Set으로 변경했습니다

2024-02-24 09:15 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoTicket.kt
> +        return numbers.binarySearch(target) >= 0
로또 번호를 set으로 바꾸면서 contain을 다시 사용하도록 변경했습니다

2024-02-24 09:16 UTC, Heejun-0219 commented on src/main/kotlin/domain/generator/AutoLottoGenerator.kt
> +        val bonusNumber = (numberRange - numbers.toSet()).shuffled().first()
정말 모르는 메서드가 많은거 같습니다 ㅠㅠ

2024-02-24 09:17 UTC, Heejun-0219 commented on src/test/kotlin/domain/generator/AutoLottoGeneratorKotest.kt
> +class AutoLottoGeneratorKotest : FunSpec({
stringspec, behaviorspec 더 공부해보겠습니다!

2024-02-24 09:18 UTC, Heejun-0219 commented on src/test/kotlin/domain/generator/AutoLottoGeneratorTest.kt
> +        val generator = AutoLottoGenerator()
아하,,,, 정상 테스트로 넣었는데 랜덤성이 포함되는 테스트는 아에 배제하는게 좋을까요?

2024-02-24 09:19 UTC, Heejun-0219 commented
정말 길고,,,, 오래 걸렸던 피드백,,, 부탁드립니다. 
저도 오랜만에 코드를 보느라 헷갈리고 남겨주신 피드백이 올바르게 수정되었는지 확실하지 않지만,,
부탁드리겠습니다 ㅠㅠ

2024-02-24 09:21 UTC, Heejun-0219 commented
로또 번호를 TreeSet으로 변경하니까 테스트 코드가 너무 더러워서 보고 싶지 않아서 고민하고 다시 생각하기가 오래 걸렸던 거 같습니다

2024-02-24 17:30 UTC, konempty requested changes
거의 다온것 같아요..!
진짜 조금만더 수정부탁드립니다~!

2024-02-24 17:30 UTC, konempty commented on build.gradle.kts
> +    testImplementation("io.mockk:mockk:1.12.0")
kotlin mock라이브러리에는 mockk도 있고 kotlin mockito도 있는데 Mockk을 선택한 이유가 있을까요??

2024-02-24 17:30 UTC, konempty commented on src/main/kotlin/controller/UserInputController.kt
> +class UserInputController(
으흠 우테코 들으셨을때 프로그램 전역적인 흐름을 관리하는 역할이 컨트롤러의 역할이라고 지도 받지 않으셨을까요..?
요 클래스는 지엽적인 유저 인풋만 관리하는데 컨트롤러라는 이름이 어울릴까요?? ㅎㅎㅎ..

2024-02-24 17:30 UTC, konempty commented on src/main/kotlin/domain/LottoPrizeCalculator.kt
> +    private fun checkRank(results: List<Pair<Int, Boolean>>): LottoResult {
List<Pair<Int, Boolean>>라는 선언은 우아하지 않은데 일급컬렉션화 하면 좋을것 같아요~!
일급컬렉션화 하면서 필요한 메소드도 내재화 하면 좋을것 같구요!

2024-02-24 17:30 UTC, konempty commented on src/main/kotlin/domain/LottoResult.kt
> +        return totalEarning.toDouble() / purchaseAmount
percent라면 100을 곱해주는 과정이 있어야 하지 않을까요??

2024-02-24 17:30 UTC, konempty commented on src/main/kotlin/domain/LottoTicket.kt
> +open class LottoTicket(val numbers: Set<Int>) {
Set\<Int> 대신 Set\<LottoNumber>가 되면 좋을것 같아요~!

2024-02-24 17:30 UTC, konempty commented on src/main/kotlin/domain/WinningLotto.kt
> +    val bonusNumber: Int,
여기도 마찬가지구요 ㅎㅎ

2024-02-24 17:30 UTC, konempty commented on src/main/kotlin/domain/ticket/BonusLottoNumbers.kt
> +class BonusLottoNumbers(private val numbers: Set<Int>) {
이름이 클래스의 의도를 잘 나타내지 못하네요 ㅠㅠ
보너스 번호 검증이라는 의도가 잘 나타냈으면 좋을것 같구요
요건 좀 고민 되긴 하는데 WinningLotto가 요 역할을 가지고 있어도 괜찮지 않을까? 라는 생각이 드네요 ㅋㅋㅋ

2024-02-24 17:30 UTC, konempty commented on src/main/kotlin/domain/ticket/LottoNumbers.kt
> +class LottoNumbers(private val numbers: Set<Int>) {
BonusLottoNumbers와 같은 이슈를 공유하네요

2024-02-24 17:30 UTC, konempty commented on src/test/kotlin/domain/LottoPrizeCalculatorTest.kt
> +        val bonusNumber = 7
현재는 그럴일이 없지만 만약에 로또 번호가 6개가 아니라 7개가 되었다고 가정 해봅시다
그렇다면 테스트의 의미는 변하지 않지만 로또 번호 개수가 변했기 때문에 여기가 수정이 되어야 겠죠?
하지만 그건 테스트 자동화 관점에서 뭔가 아쉬운것 같아요 ㅎㅎ..
```kotlin
val winningNumbers = LottoMinNumber until (LottoMinNumber + LottoNumberSize)
val bonusNumber = LottoMinNumber + LottoNumberSize 
```
요렇게 하면 도메인 변화에 좀더 유연하게 대처되는 코드가 되지 않을까요 ㅎㅎ

요 아래 코드 들도 전부 해당하는 내용이예요

2024-02-24 17:30 UTC, konempty commented on src/test/kotlin/domain/LottoPrizeCalculatorTest.kt
> +        test("Mixed ticket results yield correct prize distribution") {
ㅋㅋㅋㅋ 요건 갠취인데
저는 영어를 잘 못해서 테스트는 보기 좋게 한글로 적어두는걸 선호하구요
저희 부서 컨벤션도 한글로 적는게 룰이예요

2024-02-24 17:30 UTC, konempty commented on src/test/kotlin/domain/LottoTicketTest.kt
> +    "범위를 벗어난 숫자 포함 로또 실패 테스트" {
요건 Lotto 클래스의 역할 테스트 일까요
LottoNumber 클래스의 역할 테스트 일까요??

2024-02-24 17:30 UTC, konempty commented on src/test/kotlin/domain/generator/AutoLottoGeneratorTest.kt
> +        lottoTicket.match(lottoTicket) shouldBeExactly LottoConstant.LOTTO_TICKET_SIZE
이건 로또 생성기의 테스트 일까요
로또 도메인의 테스트 일까요?

2024-02-24 17:30 UTC, konempty commented on src/test/kotlin/domain/generator/AutoLottoGeneratorTest.kt
> +        lottoTicket.numbers.distinct().size shouldBe lottoTicket.numbers.size
lottoTicket.numbers.size대신 LottoConstant.LOTTO_TICKET_SIZE와 비교하는게 더 의도를 잘 나타낼것 같아요!

2024-02-24 17:30 UTC, konempty commented on src/test/kotlin/domain/generator/AutoLottoGeneratorTest.kt
> +        lottoTicket.numbers.shouldBeSorted()
요건 갠취라 적용하진 않으셔도 되고 그냥 제 개인적인 의견 전달입니다!
numbers가 Set형이니까 shouldBeSorted() 테스트는 Set에 대한 테스트라고 보는게 맞을것 같구요
그건 테스트 범위를 넘어선다고 생각해요..!

2024-02-24 17:30 UTC, konempty commented on src/test/kotlin/domain/generator/ManualLottoGeneratorTest.kt
> +    }
최대한 올렸다면 OK입니다~!

2024-02-25 05:40 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoPrizeCalculator.kt
> +    private fun checkRank(results: List<Pair<Int, Boolean>>): LottoResult {
```kotlin
class LottoCheckRank(private val results: List<Pair<Int, Boolean>>) {
    fun checkRank(): LottoResult {
        val lottoResult =
            results.groupBy { (matchCount, hasBonus) ->
                PrizeCategory.getRank(matchCount, hasBonus)
            }.mapValues { (_, value) -> value.size }.filterKeys { it != PrizeCategory.NONE }

        return LottoResult(lottoResult)
    }
}
```

이렇게 나눴는데, 이러면 너무 클래스가 나눠지는건 아닐까 고민입니다

2024-02-25 05:45 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoResult.kt
> +        return totalEarning.toDouble() / purchaseAmount
아하,,,, 치명적인 문제가 있었네요

2024-02-25 06:16 UTC, Heejun-0219 commented on src/main/kotlin/domain/LottoTicket.kt
> +open class LottoTicket(val numbers: Set<Int>) {
변경 후에 
```kotlin 
    fun hasBonus(target: Int): Boolean {
        return numbers.contains(LottoNumber(target))
    }
```
코드를 
```kotlin return numbers.any { it.number == target }```
```kotlin return numbers.contains(LottoNumber(target))```
둘 중에 고민하게 되었습니다. 위의 코드가 가독성이 더 좋아 보이지만 시간복잡도에서 단점이 있다고 생각합니다. 혹시 확장함수와 같이 다른 방식으로 표현하는 것이 좋을지 고민입니다.

2024-02-25 07:27 UTC, Heejun-0219 commented on src/main/kotlin/domain/ticket/BonusLottoNumbers.kt
> +class BonusLottoNumbers(private val numbers: Set<Int>) {
전에 value class를 이해 못 해서 모든 자료구조를 value class로 나타내야 한다고 생각해서 남겨뒀습니다
삭제하고 WinningLotto로 옮겼습니다!

2024-02-25 13:20 UTC, konempty commented on src/main/kotlin/domain/LottoPrizeCalculator.kt
> +    private fun checkRank(results: List<Pair<Int, Boolean>>): LottoResult {
좀 극단적인 리팩토링이지만 그래도 일급컬렉션을 적극적으로 사용해보시면 좋을것 같아요~!

2024-02-25 13:21 UTC, konempty commented on src/main/kotlin/domain/LottoTicket.kt
> +open class LottoTicket(val numbers: Set<Int>) {
```kotlin
val targetNumber = LottoNumber(target)
return numbers.contains(targetNumber)
```

요정도로 하면 될것 같아요!

2024-02-25 14:49 UTC, Heejun-0219 commented on src/test/kotlin/domain/generator/AutoLottoGeneratorTest.kt
> +        lottoTicket.numbers.distinct().size shouldBe lottoTicket.numbers.size
의도를 잘 나타내는 테스트
감사합니다!

2024-02-25 14:57 UTC, Heejun-0219 commented on src/main/kotlin/controller/UserInputController.kt
> +class UserInputController(
`LottoInputHandler`로 변경해보았습니다!

2024-02-25 15:04 UTC, Heejun-0219 commented on build.gradle.kts
> +    testImplementation("io.mockk:mockk:1.12.0")
둘 다 사용해보지는 않아서 선호도 때문에 고른 것은 아니고 mockk이 코틀린과 고유기능과 호환성이 더 좋다고 봐서 사용했습니다!

2024-02-25 15:23 UTC, Heejun-0219 commented on src/test/kotlin/domain/generator/AutoLottoGeneratorTest.kt
> +        lottoTicket.numbers.shouldBeSorted()
AutoGenerator의 자동 정렬 기능을 테스트하는 거라고 생각해서 넣어놨는데 테스트 범위를 정하는 것도 잘 생각해 보겠습니다 감사합니다

2024-02-25 15:28 UTC, Heejun-0219 commented on src/test/kotlin/domain/generator/AutoLottoGeneratorTest.kt
> +        lottoTicket.match(lottoTicket) shouldBeExactly LottoConstant.LOTTO_TICKET_SIZE
이건 확실히 범위를 넘어선 테스트인 거 같습니다

2024-02-25 15:29 UTC, Heejun-0219 commented on src/test/kotlin/domain/LottoTicketTest.kt
> +    "범위를 벗어난 숫자 포함 로또 실패 테스트" {
LottoNumber 클래스 역할 테스트라고 생각합니다,,

2024-02-25 15:57 UTC, Heejun-0219 commented on src/test/kotlin/domain/LottoPrizeCalculatorTest.kt
> +        test("Mixed ticket results yield correct prize distribution") {
테스트 코드도 정말 배워갈 점이 많은 거 같습니다,,ㅎㅎ

2024-02-25 17:33 UTC, Heejun-0219 commented on src/test/kotlin/domain/LottoPrizeCalculatorTest.kt
> +        val bonusNumber = 7
테스트 코드 변경해 보았습니다! 훨씬 코드도 눈에 잘 들어오는 거 같습니다 감사합니다

2024-02-26 12:57 UTC, konempty approved these changes
크 정말 고생많으셨습니다 👍 👍 
솔직히 제가 너무 빡빡하게 리뷰를 드린 부분도 많은데 
끝까지 따라오셔서 정말 만족스러웠습니다! 💯 
요번 리뷰만 적용하시면 이제 머지하셔도 좋을것 같습니다~!

2024-02-26 12:57 UTC, konempty commented on src/main/kotlin/LottoCheckRank.kt
> +}
<img width="235" alt="스크린샷 2024-02-26 오후 9 50 35" src="https://github.com/BI-kotlin-in-action-2ND/Heejune-Lotto/assets/44064530/214aca86-b2e4-4f61-aa50-84fdfb1099f8">

아하 ㅋㅋㅋ... 파일끝 개행 설정이 빠졌네요
이전에 리뷰 드렸던것 같은데 파일끝 개행이 표준방식이고 이게 없을경우
**일부** 운영체제에서는 에러가 발생할 위헝이 있습니다 ㅠㅠ

https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

요기를 참고해서 설정해주세요~!

2024-02-26 15:17 UTC, Heejun-0219 commented on src/main/kotlin/LottoCheckRank.kt
> +}
넵 변경했습니다!

2024-02-26 15:18 UTC, Heejun-0219 commented
코드 끝까지 봐주셔서 정말 감사드립니다!

2024-02-26 15:18 UTC, merged